name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⌛ Setup CI
        uses: variableland/gh-actions/actions/setup-pnpm-bun@main

      - name: 💅 Test static
        run: pnpm rr check tsc

      - name: 🧪 Test unit
        run: pnpm test

  release:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⌛ Setup CI
        uses: variableland/gh-actions/actions/setup-pnpm-bun@main

      - name: 🚀 Create release PR or publish versions
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: bunx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LEFTHOOK: 0

  preview:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ startsWith(github.head_ref, 'feat') || startsWith(github.head_ref, 'fix') }}
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⌛ Setup CI
        uses: variableland/gh-actions/actions/setup-pnpm-bun@main

      - name: 🚀 Preview release
        uses: variableland/gh-actions/actions/monorepo-preview-release@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
