name: CLI Preview

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/cli/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    if: ${{ startsWith(github.head_ref, 'feat') || startsWith(github.head_ref, 'fix') }}

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🔁 Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: 🥟 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"

      - name: 📥 Install dependencies
        run: bun i

      - name: 💅 Test Static
        run: bun dev test:static

      - name: 🧪 Test Unit
        run: bun test

      - name: 🚀 Publish preview CLI
        run: bun preview:release
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          # https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
