name: CLI Preview

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/cli/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    if: ${{ startsWith(github.head_ref, 'feat') || startsWith(github.head_ref, 'fix') }}

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: 📥 Install dependencies
        run: pnpm install

      - name: 💅 Test Static
        run: pnpm run dev test:static

      - name: 🧪 Test Unit
        run: pnpm test

      # needed to build the run-run cli
      - name: 🥟 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"

      - name: 🚀 Publish preview CLI
        run: pnpm run --filter @variableland/run-run preview:release
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
