name: Preview release

on:
  pull_request:
    branches:
      - main
    # paths:
    #   - packages/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview-release:
    runs-on: ubuntu-latest

    # if: ${{ startsWith(github.head_ref, 'feat') || startsWith(github.head_ref, 'fix') }}

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⌛ Setup CI
        uses: variableland/gh-actions/actions/setup-pnpm-bun@main

      # - name: 💅 Test static
      #   run: |
      #     bun run rr test:static
      #     bun run typecheck

      # - name: 🧪 Test unit
      #   run: bun run test

      - name: 🚀 Preview release
        uses: variableland/gh-actions/actions/monorepo-preview-release@cadb32123b9889c1bb7ff96b93a2787650e8c190
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}
          auth_token: ${{ secrets.NPM_TOKEN }}
