name: Preview release

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    if: ${{ startsWith(github.head_ref, 'feat') || startsWith(github.head_ref, 'fix') }}

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⌛ Setup CI
        uses: ./.github/actions/ci-setup

      - name: 💅 Test static
        run: |
          bun run rr test:static
          bun run typecheck

      - name: 🧪 Test unit
        run: bun run test

      - name: 🚀 Preview release
        run: bun preview:release
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
